### ISSUE TITLE
Contribute test fonts to Unicode?

### ISSUE THREAD

**Issue by brawer** [simoncozens/test-fonts#2]
Hi Simon, would you be interested in contributing your test fonts to Unicode’s [test suite for test rendering engines](https://github.com/unicode-org/text-rendering-tests)? It would need a license change; I can guide you through the process if you’re interested. (Related to #1).

**Comment by simoncozens** [comment]
Yes, happy to do so!

**Comment by brawer** [comment]
Can you send me a signed scanned copy of [this form](https://github.com/unicode-org/text-rendering-tests/raw/master/unicode_cla.pdf) to sascha@brawer.ch ?

**Comment by brawer** [comment]
Thanks again! I’ve forwarded your CLA to the Unicode secretariat, and added test cases [SFNT-1](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#SFNT-1) and [SFNT-2](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#SFNT-2) to the test suite. I’ve renamed your fonts to `TestSFNTOne` and `TestSFNTTwo`, changed their `name` table to indicate the SIL OFL-1.1 license, added Copyright by Unicode, and I’ve added your name as the font designer.

Not sure what to do about the color and sbix test cases. Currently, the test framework can’t yet handle color fonts or bitmaps. Perhaps somebody else has time to look at this?

**Comment by twardoch** [comment]
@brawer Wouldn’t it make sense to put the test data there nonetheless? That might propmpt people to actually write the testing code and improve the framework :)
